/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/app/**/*.{ts,tsx}',
    './src/containers/**/*.{ts,tsx}',
    './src/components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#e77474',
          foreground: '#ffffff',
          50:  '#fef6f6',
          100: '#fce8e8',
          200: '#fbdada',
          300: '#f7bbbb',
          400: '#f19898',
          500: '#e77474',
          600: '#d55353',
          700: '#bd2d2d',
          800: '#9a2828',
          900: '#792525',
          950: '#4f1212',
        },
        secondary: {
          DEFAULT: '#0072a1',
          foreground: '#ffffff',
          50:  '#eaf7ff',
          100: '#d2edff',
          200: '#9ddeff',
          300: '#46c7ff',
          400: '#00a9ee',
          500: '#0072a1',
          600: '#005c89',
          700: '#00486d',
          800: '#003d5b',
          900: '#03324d',
          950: '#022033',
        },
        green: {
          DEFAULT: '#61bd6c',
          foreground: '#ffffff',
          50:  '#f6fbf6',
          100: '#e9f8ea',
          200: '#d5efd8',
          300: '#b4e2ba',
          400: '#88cc90',
          500: '#61bd6c',
          600: '#40a54d',
          700: '#36823f',
          800: '#306837',
          900: '#2a5631',
          950: '#102f15',
        },
        border:      'hsl(var(--border))',
        input:       'hsl(var(--input))',
        ring:        'hsl(var(--ring))',
        background:  'hsl(var(--background))',
        foreground:  'hsl(var(--foreground))',
        destructive: {
          DEFAULT:    'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT:    'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT:    'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT:    'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT:    'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        sans: ['Pretendard', 'Apple SD Gothic Neo', 'Malgun Gothic', 'Noto Sans KR', 'sans-serif'],
      },
      boxShadow: {
        custom: 'rgba(0,0,0,0.02) 0px 12px 32px, rgba(0,0,0,0.05) 0px 0px 0px 1px',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
